services:
  backend:
    restart: on-failure
    build:
      context: ./backend
      dockerfile: .docker/Dockerfile
      args:
        - BASE_IMAGE_TAG=${BASE_IMAGE_TAG:-22-bullseye-slim}
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: .docker/Dockerfile
      args:
        - BASE_IMAGE_TAG=${BASE_IMAGE_TAG:-22-bullseye-slim}
    ports:
      - "8000:8000"
    volumes:
      - ./frontend:/app
      - /app/node_modules

networks:
  app-network:
    driver: bridge
